package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("result generated by: " + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1=new ResultTask();
        t1.run();//ℹ️normal--> always the main thread
        t1.start();//multi threading
        // ℹ️ start() internally calls run()
        // ✅Thread cannot be started twice
    }
}
